import type { PictogramEntry } from '../../types/pictogram';

export const PICTOGRAM_CATALOG: PictogramEntry[] = [
  // === PROHIBITION (P-series) ===
  { id: 'P001', category: 'prohibition', label: 'General prohibition', keywords: ['no', 'stop', 'forbidden', 'prohibited'], svgPath: '/pictograms/prohibition/P001.svg', isoCode: 'ISO 7010-P001' },
  { id: 'P002', category: 'prohibition', label: 'No smoking', keywords: ['smoke', 'cigarette', 'tobacco', 'no smoking'], svgPath: '/pictograms/prohibition/P002.svg', isoCode: 'ISO 7010-P002' },
  { id: 'P003', category: 'prohibition', label: 'No open flame; No fire, open ignition source or smoking', keywords: ['fire', 'flame', 'ignition', 'smoking', 'open flame'], svgPath: '/pictograms/prohibition/P003.svg', isoCode: 'ISO 7010-P003' },
  { id: 'P004', category: 'prohibition', label: 'No thoroughfare', keywords: ['pedestrian', 'walk', 'thoroughfare', 'no entry'], svgPath: '/pictograms/prohibition/P004.svg', isoCode: 'ISO 7010-P004' },
  { id: 'P005', category: 'prohibition', label: 'Not drinking water', keywords: ['water', 'drink', 'tap', 'potable'], svgPath: '/pictograms/prohibition/P005.svg', isoCode: 'ISO 7010-P005' },
  { id: 'P006', category: 'prohibition', label: 'No access for forklift trucks and other industrial vehicles', keywords: ['forklift', 'truck', 'vehicle', 'industrial'], svgPath: '/pictograms/prohibition/P006.svg', isoCode: 'ISO 7010-P006' },
  { id: 'P007', category: 'prohibition', label: 'No access for people with active implanted cardiac devices', keywords: ['pacemaker', 'cardiac', 'implant', 'heart device'], svgPath: '/pictograms/prohibition/P007.svg', isoCode: 'ISO 7010-P007' },
  { id: 'P008', category: 'prohibition', label: 'No metallic articles or watches', keywords: ['metal', 'jewelry', 'watch', 'ring'], svgPath: '/pictograms/prohibition/P008.svg', isoCode: 'ISO 7010-P008' },
  { id: 'P009', category: 'prohibition', label: 'No climbing', keywords: ['climbing', 'climb', 'ladder', 'fence'], svgPath: '/pictograms/prohibition/P009.svg', isoCode: 'ISO 7010-P009' },
  { id: 'P010', category: 'prohibition', label: 'Do not touch', keywords: ['touch', 'hand', 'contact', 'do not touch'], svgPath: '/pictograms/prohibition/P010.svg', isoCode: 'ISO 7010-P010' },
  { id: 'P011', category: 'prohibition', label: 'Do not extinguish with water', keywords: ['water', 'extinguish', 'fire', 'spray'], svgPath: '/pictograms/prohibition/P011.svg', isoCode: 'ISO 7010-P011' },
  { id: 'P012', category: 'prohibition', label: 'No heavy load', keywords: ['heavy', 'load', 'weight', 'floor'], svgPath: '/pictograms/prohibition/P012.svg', isoCode: 'ISO 7010-P012' },
  { id: 'P013', category: 'prohibition', label: 'No activated mobile phones', keywords: ['phone', 'mobile', 'cell', 'wireless'], svgPath: '/pictograms/prohibition/P013.svg', isoCode: 'ISO 7010-P013' },
  { id: 'P014', category: 'prohibition', label: 'No access for people with metallic implants', keywords: ['implant', 'metallic', 'medical', 'magnetic'], svgPath: '/pictograms/prohibition/P014.svg', isoCode: 'ISO 7010-P014' },
  { id: 'P015', category: 'prohibition', label: 'No reaching in', keywords: ['reach', 'hand', 'opening', 'danger'], svgPath: '/pictograms/prohibition/P015.svg', isoCode: 'ISO 7010-P015' },
  { id: 'P016', category: 'prohibition', label: 'Do not spray with water', keywords: ['spray', 'water', 'hose', 'wet'], svgPath: '/pictograms/prohibition/P016.svg', isoCode: 'ISO 7010-P016' },
  { id: 'P017', category: 'prohibition', label: 'No pushing', keywords: ['push', 'shove', 'force', 'prohibited'], svgPath: '/pictograms/prohibition/P017.svg', isoCode: 'ISO 7010-P017' },
  { id: 'P018', category: 'prohibition', label: 'No sitting', keywords: ['sit', 'seat', 'chair', 'bench'], svgPath: '/pictograms/prohibition/P018.svg', isoCode: 'ISO 7010-P018' },
  { id: 'P019', category: 'prohibition', label: 'No stepping on surface', keywords: ['step', 'surface', 'stand', 'weight'], svgPath: '/pictograms/prohibition/P019.svg', isoCode: 'ISO 7010-P019' },
  { id: 'P020', category: 'prohibition', label: 'Do not use lift in the event of fire', keywords: ['lift', 'elevator', 'fire', 'stairs'], svgPath: '/pictograms/prohibition/P020.svg', isoCode: 'ISO 7010-P020' },
  { id: 'P021', category: 'prohibition', label: 'No dogs', keywords: ['dog', 'pet', 'animal', 'prohibited'], svgPath: '/pictograms/prohibition/P021.svg', isoCode: 'ISO 7010-P021' },
  { id: 'P022', category: 'prohibition', label: 'No eating or drinking', keywords: ['eat', 'drink', 'food', 'beverage'], svgPath: '/pictograms/prohibition/P022.svg', isoCode: 'ISO 7010-P022' },
  { id: 'P023', category: 'prohibition', label: 'Do not obstruct', keywords: ['obstruct', 'block', 'path', 'access'], svgPath: '/pictograms/prohibition/P023.svg', isoCode: 'ISO 7010-P023' },
  { id: 'P024', category: 'prohibition', label: 'Do not walk or stand here', keywords: ['walk', 'stand', 'surface', 'danger'], svgPath: '/pictograms/prohibition/P024.svg', isoCode: 'ISO 7010-P024' },
  { id: 'P025', category: 'prohibition', label: 'Do not use this incomplete scaffold', keywords: ['scaffold', 'incomplete', 'construction', 'unsafe'], svgPath: '/pictograms/prohibition/P025.svg', isoCode: 'ISO 7010-P025' },
  { id: 'P026', category: 'prohibition', label: 'Do not use this device in a bathtub, shower or water-filled reservoir', keywords: ['bathtub', 'shower', 'water', 'electrical device'], svgPath: '/pictograms/prohibition/P026.svg', isoCode: 'ISO 7010-P026' },
  { id: 'P027', category: 'prohibition', label: 'Do not use this lift for people', keywords: ['lift', 'elevator', 'people', 'freight'], svgPath: '/pictograms/prohibition/P027.svg', isoCode: 'ISO 7010-P027' },
  { id: 'P028', category: 'prohibition', label: 'Do not wear gloves', keywords: ['gloves', 'wear', 'hands', 'prohibited'], svgPath: '/pictograms/prohibition/P028.svg', isoCode: 'ISO 7010-P028' },
  { id: 'P029', category: 'prohibition', label: 'No photography', keywords: ['photo', 'camera', 'picture', 'photography'], svgPath: '/pictograms/prohibition/P029.svg', isoCode: 'ISO 7010-P029' },
  { id: 'P030', category: 'prohibition', label: 'Do not tie knots in rope', keywords: ['knot', 'rope', 'tie', 'cord'], svgPath: '/pictograms/prohibition/P030.svg', isoCode: 'ISO 7010-P030' },
  { id: 'P031', category: 'prohibition', label: 'Do not alter the state of the switch', keywords: ['switch', 'alter', 'toggle', 'electrical'], svgPath: '/pictograms/prohibition/P031.svg', isoCode: 'ISO 7010-P031' },
  { id: 'P032', category: 'prohibition', label: 'Do not use for face grinding', keywords: ['grinding', 'face', 'disc', 'tool'], svgPath: '/pictograms/prohibition/P032.svg', isoCode: 'ISO 7010-P032' },
  { id: 'P033', category: 'prohibition', label: 'Do not use for wet grinding', keywords: ['grinding', 'wet', 'machine', 'tool'], svgPath: '/pictograms/prohibition/P033.svg', isoCode: 'ISO 7010-P033' },
  { id: 'P034', category: 'prohibition', label: 'Do not use with hand-held grinder', keywords: ['grinder', 'hand-held', 'machine', 'tool'], svgPath: '/pictograms/prohibition/P034.svg', isoCode: 'ISO 7010-P034' },
  { id: 'P035', category: 'prohibition', label: 'Do not use with hand-held cutting machine', keywords: ['cutting', 'hand-held', 'machine', 'tool'], svgPath: '/pictograms/prohibition/P035.svg', isoCode: 'ISO 7010-P035' },
  { id: 'P036', category: 'prohibition', label: 'Do not sharpen/hone', keywords: ['sharpen', 'hone', 'blade', 'tool'], svgPath: '/pictograms/prohibition/P036.svg', isoCode: 'ISO 7010-P036' },
  { id: 'P037', category: 'prohibition', label: 'No sitting on railing/guardrail', keywords: ['railing', 'guardrail', 'sitting', 'lean'], svgPath: '/pictograms/prohibition/P037.svg', isoCode: 'ISO 7010-P037' },
  { id: 'P038', category: 'prohibition', label: 'No climbing', keywords: ['climbing', 'climb', 'ladder', 'fence'], svgPath: '/pictograms/prohibition/P038.svg', isoCode: 'ISO 7010-P038' },
  { id: 'P039', category: 'prohibition', label: 'No access for tall vehicles', keywords: ['tall', 'vehicle', 'height', 'clearance'], svgPath: '/pictograms/prohibition/P039.svg', isoCode: 'ISO 7010-P039' },
  { id: 'P040', category: 'prohibition', label: 'Do not jump down', keywords: ['jump', 'down', 'fall', 'leap'], svgPath: '/pictograms/prohibition/P040.svg', isoCode: 'ISO 7010-P040' },
  { id: 'P041', category: 'prohibition', label: 'No animals', keywords: ['animal', 'pet', 'dog', 'prohibited'], svgPath: '/pictograms/prohibition/P041.svg', isoCode: 'ISO 7010-P041' },
  { id: 'P042', category: 'prohibition', label: 'Do not store food or beverages', keywords: ['food', 'beverage', 'store', 'eating'], svgPath: '/pictograms/prohibition/P042.svg', isoCode: 'ISO 7010-P042' },
  { id: 'P043', category: 'prohibition', label: 'Do not block', keywords: ['block', 'obstruct', 'path', 'access'], svgPath: '/pictograms/prohibition/P043.svg', isoCode: 'ISO 7010-P043' },
  { id: 'P044', category: 'prohibition', label: 'No open flame and no smoking', keywords: ['flame', 'fire', 'smoking', 'ignition'], svgPath: '/pictograms/prohibition/P044.svg', isoCode: 'ISO 7010-P044' },
  { id: 'P045', category: 'prohibition', label: 'Do not play on or around', keywords: ['play', 'children', 'danger', 'area'], svgPath: '/pictograms/prohibition/P045.svg', isoCode: 'ISO 7010-P045' },
  { id: 'P046', category: 'prohibition', label: 'Not to be used in residential areas', keywords: ['residential', 'housing', 'neighborhood', 'area'], svgPath: '/pictograms/prohibition/P046.svg', isoCode: 'ISO 7010-P046' },
  { id: 'P047', category: 'prohibition', label: 'Do not use outdoors', keywords: ['outdoors', 'outside', 'weather', 'rain'], svgPath: '/pictograms/prohibition/P047.svg', isoCode: 'ISO 7010-P047' },
  { id: 'P048', category: 'prohibition', label: 'Do not look directly at sun', keywords: ['sun', 'eyes', 'look', 'solar'], svgPath: '/pictograms/prohibition/P048.svg', isoCode: 'ISO 7010-P048' },
  { id: 'P049', category: 'prohibition', label: 'Do not spray with water', keywords: ['spray', 'water', 'hose', 'wet'], svgPath: '/pictograms/prohibition/P049.svg', isoCode: 'ISO 7010-P049' },
  { id: 'P050', category: 'prohibition', label: 'Do not walk on surface', keywords: ['walk', 'surface', 'floor', 'step'], svgPath: '/pictograms/prohibition/P050.svg', isoCode: 'ISO 7010-P050' },
  { id: 'P051', category: 'prohibition', label: 'No access to swimming non-swimmers', keywords: ['swimming', 'pool', 'non-swimmer', 'water'], svgPath: '/pictograms/prohibition/P051.svg', isoCode: 'ISO 7010-P051' },
  { id: 'P052', category: 'prohibition', label: 'Do not use for ski jumping', keywords: ['ski', 'jumping', 'winter', 'sport'], svgPath: '/pictograms/prohibition/P052.svg', isoCode: 'ISO 7010-P052' },
  { id: 'P053', category: 'prohibition', label: 'No entry when door is open', keywords: ['door', 'entry', 'open', 'access'], svgPath: '/pictograms/prohibition/P053.svg', isoCode: 'ISO 7010-P053' },
  { id: 'P054', category: 'prohibition', label: 'No tent camping', keywords: ['tent', 'camping', 'camp', 'outdoor'], svgPath: '/pictograms/prohibition/P054.svg', isoCode: 'ISO 7010-P054' },
  { id: 'P055', category: 'prohibition', label: 'No ice skating', keywords: ['ice', 'skating', 'winter', 'rink'], svgPath: '/pictograms/prohibition/P055.svg', isoCode: 'ISO 7010-P055' },
  { id: 'P056', category: 'prohibition', label: 'No stopping on tracks', keywords: ['tracks', 'stopping', 'rail', 'train'], svgPath: '/pictograms/prohibition/P056.svg', isoCode: 'ISO 7010-P056' },
  { id: 'P057', category: 'prohibition', label: 'Do not modify plug', keywords: ['plug', 'modify', 'electrical', 'socket'], svgPath: '/pictograms/prohibition/P057.svg', isoCode: 'ISO 7010-P057' },
  { id: 'P058', category: 'prohibition', label: 'Do not fill more than specified', keywords: ['fill', 'overflow', 'container', 'level'], svgPath: '/pictograms/prohibition/P058.svg', isoCode: 'ISO 7010-P058' },
  { id: 'P059', category: 'prohibition', label: 'Do not use in confined spaces', keywords: ['confined', 'space', 'enclosed', 'ventilation'], svgPath: '/pictograms/prohibition/P059.svg', isoCode: 'ISO 7010-P059' },
  { id: 'P060', category: 'prohibition', label: 'No body surfing', keywords: ['body surfing', 'wave', 'beach', 'water'], svgPath: '/pictograms/prohibition/P060.svg', isoCode: 'ISO 7010-P060' },
  { id: 'P061', category: 'prohibition', label: 'Do not play in water', keywords: ['play', 'water', 'children', 'pool'], svgPath: '/pictograms/prohibition/P061.svg', isoCode: 'ISO 7010-P061' },
  { id: 'P062', category: 'prohibition', label: 'Do not pick flowers', keywords: ['flowers', 'pick', 'plants', 'garden'], svgPath: '/pictograms/prohibition/P062.svg', isoCode: 'ISO 7010-P062' },
  { id: 'P063', category: 'prohibition', label: 'No parachuting', keywords: ['parachute', 'skydiving', 'jump', 'air'], svgPath: '/pictograms/prohibition/P063.svg', isoCode: 'ISO 7010-P063' },
  { id: 'P064', category: 'prohibition', label: 'Do not disassemble', keywords: ['disassemble', 'take apart', 'repair', 'open'], svgPath: '/pictograms/prohibition/P064.svg', isoCode: 'ISO 7010-P064' },
  { id: 'P065', category: 'prohibition', label: 'Do not touch moving parts', keywords: ['moving parts', 'touch', 'machinery', 'rotating'], svgPath: '/pictograms/prohibition/P065.svg', isoCode: 'ISO 7010-P065' },
  { id: 'P066', category: 'prohibition', label: 'No motorcraft', keywords: ['motorcraft', 'boat', 'motor', 'watercraft'], svgPath: '/pictograms/prohibition/P066.svg', isoCode: 'ISO 7010-P066' },
  { id: 'P067', category: 'prohibition', label: 'No bungee jumping', keywords: ['bungee', 'jumping', 'extreme', 'sport'], svgPath: '/pictograms/prohibition/P067.svg', isoCode: 'ISO 7010-P067' },
  { id: 'P068', category: 'prohibition', label: 'Do not fold', keywords: ['fold', 'bend', 'crease', 'material'], svgPath: '/pictograms/prohibition/P068.svg', isoCode: 'ISO 7010-P068' },
  { id: 'P069', category: 'prohibition', label: 'Do not expose to sunlight', keywords: ['sunlight', 'sun', 'UV', 'exposure'], svgPath: '/pictograms/prohibition/P069.svg', isoCode: 'ISO 7010-P069' },
  { id: 'P070', category: 'prohibition', label: 'Do not eat or drink', keywords: ['eat', 'drink', 'food', 'beverage'], svgPath: '/pictograms/prohibition/P070.svg', isoCode: 'ISO 7010-P070' },
  { id: 'P071', category: 'prohibition', label: 'No drones', keywords: ['drone', 'UAV', 'flying', 'unmanned'], svgPath: '/pictograms/prohibition/P071.svg', isoCode: 'ISO 7010-P071' },
  { id: 'P072', category: 'prohibition', label: 'No ball games', keywords: ['ball', 'games', 'sport', 'playing'], svgPath: '/pictograms/prohibition/P072.svg', isoCode: 'ISO 7010-P072' },
  { id: 'P073', category: 'prohibition', label: 'Do not block ventilation openings', keywords: ['ventilation', 'openings', 'block', 'airflow'], svgPath: '/pictograms/prohibition/P073.svg', isoCode: 'ISO 7010-P073' },
  { id: 'P074', category: 'prohibition', label: 'No paragliding', keywords: ['paragliding', 'flying', 'air', 'sport'], svgPath: '/pictograms/prohibition/P074.svg', isoCode: 'ISO 7010-P074' },
  { id: 'P075', category: 'prohibition', label: 'No horseback riding', keywords: ['horse', 'riding', 'equestrian', 'animal'], svgPath: '/pictograms/prohibition/P075.svg', isoCode: 'ISO 7010-P075' },
  { id: 'P080', category: 'prohibition', label: 'Do not vape', keywords: ['vape', 'e-cigarette', 'vaping', 'electronic'], svgPath: '/pictograms/prohibition/P080.svg', isoCode: 'ISO 7010-P080' },
  { id: 'P081', category: 'prohibition', label: 'No e-scooters', keywords: ['scooter', 'e-scooter', 'electric', 'vehicle'], svgPath: '/pictograms/prohibition/P081.svg', isoCode: 'ISO 7010-P081' },

  // === WARNING (W-series) ===
  { id: 'W001', category: 'warning', label: 'General warning sign', keywords: ['warning', 'caution', 'attention', 'danger'], svgPath: '/pictograms/warning/W001.svg', isoCode: 'ISO 7010-W001' },
  { id: 'W002', category: 'warning', label: 'Warning; explosive material', keywords: ['explosive', 'bomb', 'blast', 'detonation'], svgPath: '/pictograms/warning/W002.svg', isoCode: 'ISO 7010-W002' },
  { id: 'W003', category: 'warning', label: 'Warning; radioactive material or ionizing radiation', keywords: ['radioactive', 'radiation', 'nuclear', 'ionizing'], svgPath: '/pictograms/warning/W003.svg', isoCode: 'ISO 7010-W003' },
  { id: 'W004', category: 'warning', label: 'Warning; laser beam', keywords: ['laser', 'beam', 'light', 'optical'], svgPath: '/pictograms/warning/W004.svg', isoCode: 'ISO 7010-W004' },
  { id: 'W005', category: 'warning', label: 'Warning; non-ionizing radiation', keywords: ['radiation', 'electromagnetic', 'microwave', 'non-ionizing'], svgPath: '/pictograms/warning/W005.svg', isoCode: 'ISO 7010-W005' },
  { id: 'W006', category: 'warning', label: 'Warning; magnetic field', keywords: ['magnetic', 'magnet', 'field', 'MRI'], svgPath: '/pictograms/warning/W006.svg', isoCode: 'ISO 7010-W006' },
  { id: 'W007', category: 'warning', label: 'Warning; obstacle at ground level', keywords: ['obstacle', 'trip', 'stumble', 'ground level'], svgPath: '/pictograms/warning/W007.svg', isoCode: 'ISO 7010-W007' },
  { id: 'W008', category: 'warning', label: 'Warning; drop (fall)', keywords: ['fall', 'drop', 'cliff', 'edge'], svgPath: '/pictograms/warning/W008.svg', isoCode: 'ISO 7010-W008' },
  { id: 'W009', category: 'warning', label: 'Warning; biological hazard', keywords: ['biohazard', 'biological', 'virus', 'bacteria'], svgPath: '/pictograms/warning/W009.svg', isoCode: 'ISO 7010-W009' },
  { id: 'W010', category: 'warning', label: 'Warning; low temperature/freezing conditions', keywords: ['cold', 'freeze', 'frost', 'temperature'], svgPath: '/pictograms/warning/W010.svg', isoCode: 'ISO 7010-W010' },
  { id: 'W011', category: 'warning', label: 'Warning; slippery surface', keywords: ['slip', 'slippery', 'wet', 'floor'], svgPath: '/pictograms/warning/W011.svg', isoCode: 'ISO 7010-W011' },
  { id: 'W012', category: 'warning', label: 'Warning; electricity', keywords: ['electric', 'shock', 'voltage', 'high voltage'], svgPath: '/pictograms/warning/W012.svg', isoCode: 'ISO 7010-W012' },
  { id: 'W013', category: 'warning', label: 'Warning; guard dog', keywords: ['dog', 'guard', 'animal', 'bite'], svgPath: '/pictograms/warning/W013.svg', isoCode: 'ISO 7010-W013' },
  { id: 'W014', category: 'warning', label: 'Warning; forklift trucks and other industrial vehicles', keywords: ['forklift', 'truck', 'industrial', 'vehicle'], svgPath: '/pictograms/warning/W014.svg', isoCode: 'ISO 7010-W014' },
  { id: 'W015', category: 'warning', label: 'Warning; overhead load', keywords: ['overhead', 'load', 'crane', 'lifting'], svgPath: '/pictograms/warning/W015.svg', isoCode: 'ISO 7010-W015' },
  { id: 'W016', category: 'warning', label: 'Warning; toxic material', keywords: ['toxic', 'poison', 'skull', 'chemical'], svgPath: '/pictograms/warning/W016.svg', isoCode: 'ISO 7010-W016' },
  { id: 'W017', category: 'warning', label: 'Warning; hot surface', keywords: ['hot', 'heat', 'burn', 'surface'], svgPath: '/pictograms/warning/W017.svg', isoCode: 'ISO 7010-W017' },
  { id: 'W018', category: 'warning', label: 'Warning; automatic start-up', keywords: ['automatic', 'start-up', 'machine', 'equipment'], svgPath: '/pictograms/warning/W018.svg', isoCode: 'ISO 7010-W018' },
  { id: 'W019', category: 'warning', label: 'Warning; crushing', keywords: ['crush', 'press', 'squeeze', 'compression'], svgPath: '/pictograms/warning/W019.svg', isoCode: 'ISO 7010-W019' },
  { id: 'W020', category: 'warning', label: 'Warning; overhead obstacle', keywords: ['overhead', 'obstacle', 'head', 'clearance'], svgPath: '/pictograms/warning/W020.svg', isoCode: 'ISO 7010-W020' },
  { id: 'W021', category: 'warning', label: 'Warning; flammable material', keywords: ['flammable', 'fire', 'combustible', 'ignition'], svgPath: '/pictograms/warning/W021.svg', isoCode: 'ISO 7010-W021' },
  { id: 'W022', category: 'warning', label: 'Warning; sharp element', keywords: ['sharp', 'cut', 'blade', 'edge'], svgPath: '/pictograms/warning/W022.svg', isoCode: 'ISO 7010-W022' },
  { id: 'W023', category: 'warning', label: 'Warning; corrosive substance', keywords: ['corrosive', 'acid', 'chemical', 'burn'], svgPath: '/pictograms/warning/W023.svg', isoCode: 'ISO 7010-W023' },
  { id: 'W024', category: 'warning', label: 'Warning; hand crushing', keywords: ['crush', 'hands', 'press', 'injury'], svgPath: '/pictograms/warning/W024.svg', isoCode: 'ISO 7010-W024' },
  { id: 'W025', category: 'warning', label: 'Warning; counterweight', keywords: ['counterweight', 'weight', 'balance', 'swing'], svgPath: '/pictograms/warning/W025.svg', isoCode: 'ISO 7010-W025' },
  { id: 'W026', category: 'warning', label: 'Warning; battery charging', keywords: ['battery', 'charging', 'electric', 'acid'], svgPath: '/pictograms/warning/W026.svg', isoCode: 'ISO 7010-W026' },
  { id: 'W027', category: 'warning', label: 'Warning; optical radiation', keywords: ['optical', 'radiation', 'UV', 'light'], svgPath: '/pictograms/warning/W027.svg', isoCode: 'ISO 7010-W027' },
  { id: 'W028', category: 'warning', label: 'Warning; oxidizing substance', keywords: ['oxidizing', 'substance', 'chemical', 'reactive'], svgPath: '/pictograms/warning/W028.svg', isoCode: 'ISO 7010-W028' },
  { id: 'W029', category: 'warning', label: 'Warning; pressurized cylinder', keywords: ['pressurized', 'cylinder', 'gas', 'bottle'], svgPath: '/pictograms/warning/W029.svg', isoCode: 'ISO 7010-W029' },
  { id: 'W030', category: 'warning', label: 'Warning; hand crushing between press brake and material', keywords: ['hand', 'crushing', 'press brake', 'material'], svgPath: '/pictograms/warning/W030.svg', isoCode: 'ISO 7010-W030' },
  { id: 'W031', category: 'warning', label: 'Warning; rapid movement of workpiece in press brake', keywords: ['rapid', 'movement', 'workpiece', 'press brake'], svgPath: '/pictograms/warning/W031.svg', isoCode: 'ISO 7010-W031' },
  { id: 'W032', category: 'warning', label: 'Warning; counter-rotating rollers', keywords: ['rollers', 'rotating', 'nip', 'pinch'], svgPath: '/pictograms/warning/W032.svg', isoCode: 'ISO 7010-W032' },
  { id: 'W033', category: 'warning', label: 'Warning; barbed wire', keywords: ['barbed', 'wire', 'fence', 'sharp'], svgPath: '/pictograms/warning/W033.svg', isoCode: 'ISO 7010-W033' },
  { id: 'W034', category: 'warning', label: 'Warning; bull', keywords: ['bull', 'animal', 'cattle', 'charge'], svgPath: '/pictograms/warning/W034.svg', isoCode: 'ISO 7010-W034' },
  { id: 'W035', category: 'warning', label: 'Warning; falling objects', keywords: ['falling', 'objects', 'overhead', 'debris'], svgPath: '/pictograms/warning/W035.svg', isoCode: 'ISO 7010-W035' },
  { id: 'W036', category: 'warning', label: 'Warning; fragile roof', keywords: ['fragile', 'roof', 'fall through', 'weak'], svgPath: '/pictograms/warning/W036.svg', isoCode: 'ISO 7010-W036' },
  { id: 'W037', category: 'warning', label: 'Warning; run over by remote operator controlled machine', keywords: ['remote', 'controlled', 'machine', 'run over'], svgPath: '/pictograms/warning/W037.svg', isoCode: 'ISO 7010-W037' },
  { id: 'W038', category: 'warning', label: 'Warning; sudden loud noise', keywords: ['loud', 'noise', 'sudden', 'hearing'], svgPath: '/pictograms/warning/W038.svg', isoCode: 'ISO 7010-W038' },
  { id: 'W039', category: 'warning', label: 'Warning; falling ice', keywords: ['ice', 'falling', 'overhead', 'winter'], svgPath: '/pictograms/warning/W039.svg', isoCode: 'ISO 7010-W039' },
  { id: 'W040', category: 'warning', label: 'Warning; roof avalanche', keywords: ['roof', 'avalanche', 'snow', 'falling'], svgPath: '/pictograms/warning/W040.svg', isoCode: 'ISO 7010-W040' },
  { id: 'W041', category: 'warning', label: 'Warning; asphyxiating atmosphere', keywords: ['asphyxiating', 'atmosphere', 'oxygen', 'suffocation'], svgPath: '/pictograms/warning/W041.svg', isoCode: 'ISO 7010-W041' },
  { id: 'W042', category: 'warning', label: 'Warning; arc flash', keywords: ['arc', 'flash', 'electrical', 'explosion'], svgPath: '/pictograms/warning/W042.svg', isoCode: 'ISO 7010-W042' },
  { id: 'W043', category: 'warning', label: 'Warning; thin ice', keywords: ['thin ice', 'ice', 'frozen', 'break'], svgPath: '/pictograms/warning/W043.svg', isoCode: 'ISO 7010-W043' },
  { id: 'W044', category: 'warning', label: 'Warning; slipway', keywords: ['slipway', 'ramp', 'boat', 'launch'], svgPath: '/pictograms/warning/W044.svg', isoCode: 'ISO 7010-W044' },
  { id: 'W045', category: 'warning', label: 'Warning; towed water activity area', keywords: ['towed', 'water', 'activity', 'area'], svgPath: '/pictograms/warning/W045.svg', isoCode: 'ISO 7010-W045' },
  { id: 'W046', category: 'warning', label: 'Warning; surf craft area', keywords: ['surf', 'craft', 'area', 'water'], svgPath: '/pictograms/warning/W046.svg', isoCode: 'ISO 7010-W046' },
  { id: 'W047', category: 'warning', label: 'Warning; deep water', keywords: ['deep', 'water', 'drowning', 'pool'], svgPath: '/pictograms/warning/W047.svg', isoCode: 'ISO 7010-W047' },
  { id: 'W048', category: 'warning', label: 'Warning; shallow water (diving)', keywords: ['shallow', 'water', 'diving', 'depth'], svgPath: '/pictograms/warning/W048.svg', isoCode: 'ISO 7010-W048' },
  { id: 'W049', category: 'warning', label: 'Warning; submerged objects', keywords: ['submerged', 'objects', 'underwater', 'hazard'], svgPath: '/pictograms/warning/W049.svg', isoCode: 'ISO 7010-W049' },
  { id: 'W050', category: 'warning', label: 'Warning; sudden drop in swimming or leisure pools', keywords: ['sudden drop', 'pool', 'swimming', 'depth'], svgPath: '/pictograms/warning/W050.svg', isoCode: 'ISO 7010-W050' },
  { id: 'W051', category: 'warning', label: 'Warning; unprotected edge', keywords: ['unprotected', 'edge', 'fall', 'cliff'], svgPath: '/pictograms/warning/W051.svg', isoCode: 'ISO 7010-W051' },
  { id: 'W052', category: 'warning', label: 'Warning; unstable cliff edge', keywords: ['unstable', 'cliff', 'edge', 'collapse'], svgPath: '/pictograms/warning/W052.svg', isoCode: 'ISO 7010-W052' },
  { id: 'W053', category: 'warning', label: 'Warning; unstable cliff', keywords: ['unstable', 'cliff', 'collapse', 'rockfall'], svgPath: '/pictograms/warning/W053.svg', isoCode: 'ISO 7010-W053' },
  { id: 'W054', category: 'warning', label: 'Warning; shark', keywords: ['shark', 'ocean', 'marine', 'attack'], svgPath: '/pictograms/warning/W054.svg', isoCode: 'ISO 7010-W054' },
  { id: 'W055', category: 'warning', label: 'Warning; sewage effluent outfall', keywords: ['sewage', 'effluent', 'outfall', 'pollution'], svgPath: '/pictograms/warning/W055.svg', isoCode: 'ISO 7010-W055' },
  { id: 'W056', category: 'warning', label: 'Warning; tsunami hazard zone', keywords: ['tsunami', 'wave', 'hazard', 'zone'], svgPath: '/pictograms/warning/W056.svg', isoCode: 'ISO 7010-W056' },
  { id: 'W057', category: 'warning', label: 'Warning; strong currents', keywords: ['current', 'strong', 'water', 'flow'], svgPath: '/pictograms/warning/W057.svg', isoCode: 'ISO 7010-W057' },
  { id: 'W058', category: 'warning', label: 'Warning; boating area', keywords: ['boating', 'area', 'waterway', 'vessel'], svgPath: '/pictograms/warning/W058.svg', isoCode: 'ISO 7010-W058' },
  { id: 'W059', category: 'warning', label: 'Warning; sand yachting', keywords: ['sand', 'yachting', 'beach', 'wind'], svgPath: '/pictograms/warning/W059.svg', isoCode: 'ISO 7010-W059' },
  { id: 'W060', category: 'warning', label: 'Warning; incoming tides', keywords: ['incoming', 'tides', 'ocean', 'water'], svgPath: '/pictograms/warning/W060.svg', isoCode: 'ISO 7010-W060' },
  { id: 'W061', category: 'warning', label: 'Warning; quicksand or mud', keywords: ['quicksand', 'mud', 'sinking', 'soft ground'], svgPath: '/pictograms/warning/W061.svg', isoCode: 'ISO 7010-W061' },
  { id: 'W062', category: 'warning', label: 'Warning; kite surfing', keywords: ['kite', 'surfing', 'kitesurfing', 'water'], svgPath: '/pictograms/warning/W062.svg', isoCode: 'ISO 7010-W062' },
  { id: 'W063', category: 'warning', label: 'Warning; parasailing', keywords: ['parasailing', 'parachute', 'water', 'towed'], svgPath: '/pictograms/warning/W063.svg', isoCode: 'ISO 7010-W063' },
  { id: 'W064', category: 'warning', label: 'Warning; strong winds', keywords: ['strong', 'winds', 'gust', 'weather'], svgPath: '/pictograms/warning/W064.svg', isoCode: 'ISO 7010-W064' },
  { id: 'W065', category: 'warning', label: 'Warning; high surf or large breaking waves', keywords: ['surf', 'waves', 'breaking', 'ocean'], svgPath: '/pictograms/warning/W065.svg', isoCode: 'ISO 7010-W065' },
  { id: 'W066', category: 'warning', label: 'Warning; deep shelving beach', keywords: ['deep', 'shelving', 'beach', 'slope'], svgPath: '/pictograms/warning/W066.svg', isoCode: 'ISO 7010-W066' },
  { id: 'W067', category: 'warning', label: 'Warning; crocodiles, alligators or caymans', keywords: ['crocodile', 'alligator', 'cayman', 'reptile'], svgPath: '/pictograms/warning/W067.svg', isoCode: 'ISO 7010-W067' },
  { id: 'W068', category: 'warning', label: 'Warning; jellyfish', keywords: ['jellyfish', 'sting', 'ocean', 'marine'], svgPath: '/pictograms/warning/W068.svg', isoCode: 'ISO 7010-W068' },
  { id: 'W069', category: 'warning', label: 'Warning; rip/strong current', keywords: ['rip current', 'undertow', 'ocean', 'water'], svgPath: '/pictograms/warning/W069.svg', isoCode: 'ISO 7010-W069' },
  { id: 'W070', category: 'warning', label: 'Warning; stinging insects', keywords: ['insects', 'stinging', 'bee', 'wasp'], svgPath: '/pictograms/warning/W070.svg', isoCode: 'ISO 7010-W070' },
  { id: 'W071', category: 'warning', label: 'Warning; snakes', keywords: ['snake', 'reptile', 'bite', 'venomous'], svgPath: '/pictograms/warning/W071.svg', isoCode: 'ISO 7010-W071' },
  { id: 'W072', category: 'warning', label: 'Warning; confined space', keywords: ['confined', 'space', 'enclosed', 'entry'], svgPath: '/pictograms/warning/W072.svg', isoCode: 'ISO 7010-W072' },
  { id: 'W073', category: 'warning', label: 'Warning; combustible dust', keywords: ['dust', 'combustible', 'explosion', 'particles'], svgPath: '/pictograms/warning/W073.svg', isoCode: 'ISO 7010-W073' },
  { id: 'W074', category: 'warning', label: 'Warning; explosive atmosphere', keywords: ['explosive', 'atmosphere', 'gas', 'ignition'], svgPath: '/pictograms/warning/W074.svg', isoCode: 'ISO 7010-W074' },
  { id: 'W075', category: 'warning', label: 'Warning; steep ramp', keywords: ['steep', 'ramp', 'slope', 'incline'], svgPath: '/pictograms/warning/W075.svg', isoCode: 'ISO 7010-W075' },
  { id: 'W076', category: 'warning', label: 'Warning; branch falling', keywords: ['branch', 'tree', 'falling', 'overhead'], svgPath: '/pictograms/warning/W076.svg', isoCode: 'ISO 7010-W076' },
  { id: 'W077', category: 'warning', label: 'Warning; military activity area', keywords: ['military', 'activity', 'area', 'restricted'], svgPath: '/pictograms/warning/W077.svg', isoCode: 'ISO 7010-W077' },
  { id: 'W078', category: 'warning', label: 'Warning; land mines', keywords: ['mine', 'land mine', 'explosive', 'danger'], svgPath: '/pictograms/warning/W078.svg', isoCode: 'ISO 7010-W078' },
  { id: 'W079', category: 'warning', label: 'Warning; avalanche zone', keywords: ['avalanche', 'snow', 'mountain', 'zone'], svgPath: '/pictograms/warning/W079.svg', isoCode: 'ISO 7010-W079' },
  { id: 'W080', category: 'warning', label: 'Warning; rockfall', keywords: ['rock', 'fall', 'landslide', 'mountain'], svgPath: '/pictograms/warning/W080.svg', isoCode: 'ISO 7010-W080' },
  { id: 'W087', category: 'warning', label: 'Asphyxiation hazard', keywords: ['asphyxiation', 'suffocation', 'oxygen', 'breathing'], svgPath: '/pictograms/warning/W087.svg', isoCode: 'ISO 7010-W087' },
  { id: 'W088', category: 'warning', label: 'Suffocation hazard', keywords: ['suffocation', 'bag', 'plastic', 'breathing'], svgPath: '/pictograms/warning/W088.svg', isoCode: 'ISO 7010-W088' },
  { id: 'W089', category: 'warning', label: 'Risk of water pollution', keywords: ['water', 'pollution', 'contamination', 'environment'], svgPath: '/pictograms/warning/W089.svg', isoCode: 'ISO 7010-W089' },

  // === MANDATORY (M-series) ===
  { id: 'M001', category: 'mandatory', label: 'General mandatory action sign', keywords: ['mandatory', 'general', 'action', 'required'], svgPath: '/pictograms/mandatory/M001.svg', isoCode: 'ISO 7010-M001' },
  { id: 'M002', category: 'mandatory', label: 'Refer to instruction manual/booklet', keywords: ['manual', 'instructions', 'booklet', 'read'], svgPath: '/pictograms/mandatory/M002.svg', isoCode: 'ISO 7010-M002' },
  { id: 'M003', category: 'mandatory', label: 'Wear ear protection', keywords: ['ear', 'hearing', 'earmuff', 'earplug'], svgPath: '/pictograms/mandatory/M003.svg', isoCode: 'ISO 7010-M003' },
  { id: 'M004', category: 'mandatory', label: 'Wear eye protection', keywords: ['eye', 'glasses', 'goggles', 'protection'], svgPath: '/pictograms/mandatory/M004.svg', isoCode: 'ISO 7010-M004' },
  { id: 'M005', category: 'mandatory', label: 'Connect an earth terminal to the ground', keywords: ['earth', 'ground', 'terminal', 'electrical'], svgPath: '/pictograms/mandatory/M005.svg', isoCode: 'ISO 7010-M005' },
  { id: 'M006', category: 'mandatory', label: 'Disconnect mains plug from electrical outlet', keywords: ['disconnect', 'plug', 'outlet', 'electrical'], svgPath: '/pictograms/mandatory/M006.svg', isoCode: 'ISO 7010-M006' },
  { id: 'M007', category: 'mandatory', label: 'Opaque eye protection must be worn', keywords: ['opaque', 'eye', 'protection', 'tanning'], svgPath: '/pictograms/mandatory/M007.svg', isoCode: 'ISO 7010-M007' },
  { id: 'M008', category: 'mandatory', label: 'Wear safety footwear', keywords: ['boots', 'shoes', 'feet', 'steel toe'], svgPath: '/pictograms/mandatory/M008.svg', isoCode: 'ISO 7010-M008' },
  { id: 'M009', category: 'mandatory', label: 'Wear protective gloves', keywords: ['gloves', 'hand', 'protection', 'PPE'], svgPath: '/pictograms/mandatory/M009.svg', isoCode: 'ISO 7010-M009' },
  { id: 'M010', category: 'mandatory', label: 'Wear protective clothing', keywords: ['clothing', 'overalls', 'suit', 'protection'], svgPath: '/pictograms/mandatory/M010.svg', isoCode: 'ISO 7010-M010' },
  { id: 'M011', category: 'mandatory', label: 'Wash your hands', keywords: ['wash', 'hands', 'hygiene', 'clean'], svgPath: '/pictograms/mandatory/M011.svg', isoCode: 'ISO 7010-M011' },
  { id: 'M012', category: 'mandatory', label: 'Use handrail', keywords: ['handrail', 'stairs', 'railing', 'grip'], svgPath: '/pictograms/mandatory/M012.svg', isoCode: 'ISO 7010-M012' },
  { id: 'M013', category: 'mandatory', label: 'Wear a face shield', keywords: ['face', 'shield', 'visor', 'protection'], svgPath: '/pictograms/mandatory/M013.svg', isoCode: 'ISO 7010-M013' },
  { id: 'M014', category: 'mandatory', label: 'Wear head protection', keywords: ['helmet', 'hard hat', 'head', 'construction'], svgPath: '/pictograms/mandatory/M014.svg', isoCode: 'ISO 7010-M014' },
  { id: 'M015', category: 'mandatory', label: 'Wear high-visibility clothing', keywords: ['vest', 'high visibility', 'hi-vis', 'reflective'], svgPath: '/pictograms/mandatory/M015.svg', isoCode: 'ISO 7010-M015' },
  { id: 'M016', category: 'mandatory', label: 'Wear a mask', keywords: ['mask', 'face', 'covering', 'protection'], svgPath: '/pictograms/mandatory/M016.svg', isoCode: 'ISO 7010-M016' },
  { id: 'M017', category: 'mandatory', label: 'Wear respiratory protection', keywords: ['respiratory', 'mask', 'breathing', 'filter'], svgPath: '/pictograms/mandatory/M017.svg', isoCode: 'ISO 7010-M017' },
  { id: 'M018', category: 'mandatory', label: 'Wear a safety harness', keywords: ['harness', 'fall', 'height', 'rope'], svgPath: '/pictograms/mandatory/M018.svg', isoCode: 'ISO 7010-M018' },
  { id: 'M019', category: 'mandatory', label: 'Wear a welding mask', keywords: ['welding', 'mask', 'face', 'shield'], svgPath: '/pictograms/mandatory/M019.svg', isoCode: 'ISO 7010-M019' },
  { id: 'M020', category: 'mandatory', label: 'Wear safety belts', keywords: ['safety belt', 'seatbelt', 'buckle', 'restraint'], svgPath: '/pictograms/mandatory/M020.svg', isoCode: 'ISO 7010-M020' },
  { id: 'M021', category: 'mandatory', label: 'Disconnect before carrying out maintenance or repair', keywords: ['disconnect', 'maintenance', 'repair', 'power'], svgPath: '/pictograms/mandatory/M021.svg', isoCode: 'ISO 7010-M021' },
  { id: 'M022', category: 'mandatory', label: 'Use barrier cream', keywords: ['barrier cream', 'skin', 'protection', 'dermal'], svgPath: '/pictograms/mandatory/M022.svg', isoCode: 'ISO 7010-M022' },
  { id: 'M023', category: 'mandatory', label: 'Use footbridge', keywords: ['footbridge', 'bridge', 'crossing', 'walkway'], svgPath: '/pictograms/mandatory/M023.svg', isoCode: 'ISO 7010-M023' },
  { id: 'M024', category: 'mandatory', label: 'Use this walkway', keywords: ['walkway', 'path', 'pedestrian', 'route'], svgPath: '/pictograms/mandatory/M024.svg', isoCode: 'ISO 7010-M024' },
  { id: 'M025', category: 'mandatory', label: "Protect infants' eyes with opaque eye protection", keywords: ['infant', 'eyes', 'opaque', 'protection'], svgPath: '/pictograms/mandatory/M025.svg', isoCode: 'ISO 7010-M025' },
  { id: 'M026', category: 'mandatory', label: 'Use protective apron', keywords: ['apron', 'protective', 'clothing', 'PPE'], svgPath: '/pictograms/mandatory/M026.svg', isoCode: 'ISO 7010-M026' },
  { id: 'M027', category: 'mandatory', label: 'Check guard before use', keywords: ['guard', 'check', 'inspect', 'machine'], svgPath: '/pictograms/mandatory/M027.svg', isoCode: 'ISO 7010-M027' },
  { id: 'M028', category: 'mandatory', label: 'Keep locked', keywords: ['locked', 'lock', 'padlock', 'secure'], svgPath: '/pictograms/mandatory/M028.svg', isoCode: 'ISO 7010-M028' },
  { id: 'M029', category: 'mandatory', label: 'Sound horn', keywords: ['horn', 'sound', 'alert', 'warning'], svgPath: '/pictograms/mandatory/M029.svg', isoCode: 'ISO 7010-M029' },
  { id: 'M030', category: 'mandatory', label: 'Use litter bin', keywords: ['litter', 'bin', 'trash', 'waste'], svgPath: '/pictograms/mandatory/M030.svg', isoCode: 'ISO 7010-M030' },
  { id: 'M031', category: 'mandatory', label: 'Use table saw adjustable guard', keywords: ['table saw', 'guard', 'adjustable', 'machine'], svgPath: '/pictograms/mandatory/M031.svg', isoCode: 'ISO 7010-M031' },
  { id: 'M032', category: 'mandatory', label: 'Wear anti-static footwear', keywords: ['anti-static', 'footwear', 'shoes', 'ESD'], svgPath: '/pictograms/mandatory/M032.svg', isoCode: 'ISO 7010-M032' },
  { id: 'M033', category: 'mandatory', label: 'Use gas detector', keywords: ['gas', 'detector', 'monitor', 'sensor'], svgPath: '/pictograms/mandatory/M033.svg', isoCode: 'ISO 7010-M033' },
  { id: 'M034', category: 'mandatory', label: 'Read manual before use', keywords: ['manual', 'read', 'instructions', 'before use'], svgPath: '/pictograms/mandatory/M034.svg', isoCode: 'ISO 7010-M034' },
  { id: 'M035', category: 'mandatory', label: 'Push slowly', keywords: ['push', 'slowly', 'careful', 'gentle'], svgPath: '/pictograms/mandatory/M035.svg', isoCode: 'ISO 7010-M035' },
  { id: 'M036', category: 'mandatory', label: 'Lock out/tag out', keywords: ['lockout', 'tagout', 'LOTO', 'maintenance'], svgPath: '/pictograms/mandatory/M036.svg', isoCode: 'ISO 7010-M036' },
  { id: 'M037', category: 'mandatory', label: 'Use protective equipment for winter sports', keywords: ['winter', 'sports', 'protective', 'equipment'], svgPath: '/pictograms/mandatory/M037.svg', isoCode: 'ISO 7010-M037' },
  { id: 'M038', category: 'mandatory', label: 'Use seat belt', keywords: ['seat belt', 'seatbelt', 'buckle', 'vehicle'], svgPath: '/pictograms/mandatory/M038.svg', isoCode: 'ISO 7010-M038' },
  { id: 'M039', category: 'mandatory', label: 'Wear protective clothing for sports', keywords: ['sports', 'protective', 'clothing', 'gear'], svgPath: '/pictograms/mandatory/M039.svg', isoCode: 'ISO 7010-M039' },
  { id: 'M040', category: 'mandatory', label: 'Keep door closed', keywords: ['door', 'closed', 'shut', 'secure'], svgPath: '/pictograms/mandatory/M040.svg', isoCode: 'ISO 7010-M040' },
  { id: 'M041', category: 'mandatory', label: 'Keep gates closed', keywords: ['gate', 'closed', 'shut', 'secure'], svgPath: '/pictograms/mandatory/M041.svg', isoCode: 'ISO 7010-M041' },
  { id: 'M042', category: 'mandatory', label: 'Maintain three points of contact', keywords: ['three points', 'contact', 'ladder', 'climbing'], svgPath: '/pictograms/mandatory/M042.svg', isoCode: 'ISO 7010-M042' },
  { id: 'M043', category: 'mandatory', label: 'Close and secure hatches', keywords: ['hatch', 'close', 'secure', 'seal'], svgPath: '/pictograms/mandatory/M043.svg', isoCode: 'ISO 7010-M043' },
  { id: 'M044', category: 'mandatory', label: 'Fasten seat belt', keywords: ['seat belt', 'fasten', 'buckle', 'safety'], svgPath: '/pictograms/mandatory/M044.svg', isoCode: 'ISO 7010-M044' },
  { id: 'M045', category: 'mandatory', label: 'Secure gas cylinders', keywords: ['gas', 'cylinder', 'secure', 'strap'], svgPath: '/pictograms/mandatory/M045.svg', isoCode: 'ISO 7010-M045' },
  { id: 'M046', category: 'mandatory', label: 'Use safety net', keywords: ['safety net', 'fall', 'protection', 'net'], svgPath: '/pictograms/mandatory/M046.svg', isoCode: 'ISO 7010-M046' },
  { id: 'M047', category: 'mandatory', label: 'Tighten safety bindings', keywords: ['bindings', 'tighten', 'ski', 'safety'], svgPath: '/pictograms/mandatory/M047.svg', isoCode: 'ISO 7010-M047' },
  { id: 'M048', category: 'mandatory', label: 'Use vehicle restraints', keywords: ['vehicle', 'restraints', 'dock', 'loading'], svgPath: '/pictograms/mandatory/M048.svg', isoCode: 'ISO 7010-M048' },
  { id: 'M049', category: 'mandatory', label: 'Carry avalanche rescue equipment', keywords: ['avalanche', 'rescue', 'equipment', 'mountain'], svgPath: '/pictograms/mandatory/M049.svg', isoCode: 'ISO 7010-M049' },
  { id: 'M050', category: 'mandatory', label: 'Use ski binding brake', keywords: ['ski', 'binding', 'brake', 'safety'], svgPath: '/pictograms/mandatory/M050.svg', isoCode: 'ISO 7010-M050' },
  { id: 'M051', category: 'mandatory', label: 'Use ski tip safety device', keywords: ['ski', 'tip', 'safety', 'device'], svgPath: '/pictograms/mandatory/M051.svg', isoCode: 'ISO 7010-M051' },
  { id: 'M052', category: 'mandatory', label: 'Wear personal flotation device', keywords: ['flotation', 'life jacket', 'PFD', 'water'], svgPath: '/pictograms/mandatory/M052.svg', isoCode: 'ISO 7010-M052' },
  { id: 'M053', category: 'mandatory', label: 'Use safety chain', keywords: ['chain', 'safety', 'secure', 'attach'], svgPath: '/pictograms/mandatory/M053.svg', isoCode: 'ISO 7010-M053' },
  { id: 'M054', category: 'mandatory', label: 'Use adjustable guard', keywords: ['guard', 'adjustable', 'machine', 'protection'], svgPath: '/pictograms/mandatory/M054.svg', isoCode: 'ISO 7010-M054' },
  { id: 'M055', category: 'mandatory', label: 'Use guard', keywords: ['guard', 'machine', 'protection', 'safety'], svgPath: '/pictograms/mandatory/M055.svg', isoCode: 'ISO 7010-M055' },
  { id: 'M056', category: 'mandatory', label: 'Close door after entering or leaving', keywords: ['door', 'close', 'enter', 'leave'], svgPath: '/pictograms/mandatory/M056.svg', isoCode: 'ISO 7010-M056' },
  { id: 'M057', category: 'mandatory', label: 'Remove plug from socket before opening cover', keywords: ['plug', 'socket', 'cover', 'disconnect'], svgPath: '/pictograms/mandatory/M057.svg', isoCode: 'ISO 7010-M057' },
  { id: 'M058', category: 'mandatory', label: 'Remove key before maintenance or repair', keywords: ['key', 'remove', 'maintenance', 'repair'], svgPath: '/pictograms/mandatory/M058.svg', isoCode: 'ISO 7010-M058' },
  { id: 'M059', category: 'mandatory', label: 'Use fall arrest system', keywords: ['fall arrest', 'harness', 'height', 'safety'], svgPath: '/pictograms/mandatory/M059.svg', isoCode: 'ISO 7010-M059' },
  { id: 'M060', category: 'mandatory', label: 'Wear respiratory equipment', keywords: ['respiratory', 'equipment', 'breathing', 'mask'], svgPath: '/pictograms/mandatory/M060.svg', isoCode: 'ISO 7010-M060' },
  { id: 'M061', category: 'mandatory', label: 'Use handrail', keywords: ['handrail', 'stairs', 'ascending', 'descending'], svgPath: '/pictograms/mandatory/M061.svg', isoCode: 'ISO 7010-M061' },
  { id: 'M062', category: 'mandatory', label: 'Keep door closed during loading/unloading', keywords: ['door', 'closed', 'loading', 'unloading'], svgPath: '/pictograms/mandatory/M062.svg', isoCode: 'ISO 7010-M062' },
  { id: 'M068', category: 'mandatory', label: 'General mandatory action', keywords: ['mandatory', 'action', 'required', 'general'], svgPath: '/pictograms/mandatory/M068.svg', isoCode: 'ISO 7010-M068' },
  { id: 'M069', category: 'mandatory', label: 'General mandatory action', keywords: ['mandatory', 'action', 'required', 'general'], svgPath: '/pictograms/mandatory/M069.svg', isoCode: 'ISO 7010-M069' },
  { id: 'M070', category: 'mandatory', label: 'General mandatory action', keywords: ['mandatory', 'action', 'required', 'general'], svgPath: '/pictograms/mandatory/M070.svg', isoCode: 'ISO 7010-M070' },
  { id: 'M071', category: 'mandatory', label: 'General mandatory action', keywords: ['mandatory', 'action', 'required', 'general'], svgPath: '/pictograms/mandatory/M071.svg', isoCode: 'ISO 7010-M071' },
  { id: 'M072', category: 'mandatory', label: 'General mandatory action', keywords: ['mandatory', 'action', 'required', 'general'], svgPath: '/pictograms/mandatory/M072.svg', isoCode: 'ISO 7010-M072' },

  // === SAFE CONDITION (E-series) ===
  { id: 'E001', category: 'safe-condition', label: 'Emergency exit (left)', keywords: ['exit', 'emergency', 'escape', 'left'], svgPath: '/pictograms/safe-condition/E001.svg', isoCode: 'ISO 7010-E001' },
  { id: 'E002', category: 'safe-condition', label: 'Emergency exit (right)', keywords: ['exit', 'emergency', 'escape', 'right'], svgPath: '/pictograms/safe-condition/E002.svg', isoCode: 'ISO 7010-E002' },
  { id: 'E003', category: 'safe-condition', label: 'First aid', keywords: ['first aid', 'medical', 'cross', 'health'], svgPath: '/pictograms/safe-condition/E003.svg', isoCode: 'ISO 7010-E003' },
  { id: 'E004', category: 'safe-condition', label: 'Emergency telephone', keywords: ['phone', 'telephone', 'emergency', 'call'], svgPath: '/pictograms/safe-condition/E004.svg', isoCode: 'ISO 7010-E004' },
  { id: 'E007', category: 'safe-condition', label: 'Assembly point', keywords: ['assembly', 'meeting', 'gathering', 'muster'], svgPath: '/pictograms/safe-condition/E007.svg', isoCode: 'ISO 7010-E007' },
  { id: 'E008', category: 'safe-condition', label: 'Break to obtain access', keywords: ['break', 'access', 'glass', 'emergency'], svgPath: '/pictograms/safe-condition/E008.svg', isoCode: 'ISO 7010-E008' },
  { id: 'E009', category: 'safe-condition', label: 'Doctor', keywords: ['doctor', 'physician', 'medical', 'health'], svgPath: '/pictograms/safe-condition/E009.svg', isoCode: 'ISO 7010-E009' },
  { id: 'E010', category: 'safe-condition', label: 'Automated external heart defibrillator (AED)', keywords: ['AED', 'defibrillator', 'heart', 'cardiac'], svgPath: '/pictograms/safe-condition/E010.svg', isoCode: 'ISO 7010-E010' },
  { id: 'E011', category: 'safe-condition', label: 'Eyewash station', keywords: ['eye', 'wash', 'rinse', 'station'], svgPath: '/pictograms/safe-condition/E011.svg', isoCode: 'ISO 7010-E011' },
  { id: 'E012', category: 'safe-condition', label: 'Safety shower', keywords: ['shower', 'safety', 'decontamination', 'wash'], svgPath: '/pictograms/safe-condition/E012.svg', isoCode: 'ISO 7010-E012' },
  { id: 'E013', category: 'safe-condition', label: 'Stretcher', keywords: ['stretcher', 'bed', 'carry', 'patient'], svgPath: '/pictograms/safe-condition/E013.svg', isoCode: 'ISO 7010-E013' },
  { id: 'E014', category: 'safe-condition', label: 'Child seat presence and orientation detection system (CPOD)', keywords: ['child seat', 'CPOD', 'detection', 'orientation'], svgPath: '/pictograms/safe-condition/E014.svg', isoCode: 'ISO 7010-E014' },
  { id: 'E016', category: 'safe-condition', label: 'Emergency window with escape ladder', keywords: ['window', 'escape', 'ladder', 'emergency'], svgPath: '/pictograms/safe-condition/E016.svg', isoCode: 'ISO 7010-E016' },
  { id: 'E017', category: 'safe-condition', label: 'Rescue window', keywords: ['rescue', 'window', 'emergency', 'escape'], svgPath: '/pictograms/safe-condition/E017.svg', isoCode: 'ISO 7010-E017' },
  { id: 'E018', category: 'safe-condition', label: 'Turn anticlockwise to open', keywords: ['anticlockwise', 'turn', 'open', 'rotate'], svgPath: '/pictograms/safe-condition/E018.svg', isoCode: 'ISO 7010-E018' },
  { id: 'E019', category: 'safe-condition', label: 'Turn clockwise to open', keywords: ['clockwise', 'turn', 'open', 'rotate'], svgPath: '/pictograms/safe-condition/E019.svg', isoCode: 'ISO 7010-E019' },
  { id: 'E020', category: 'safe-condition', label: 'Emergency exit (arrow up left)', keywords: ['exit', 'emergency', 'up', 'left'], svgPath: '/pictograms/safe-condition/E020.svg', isoCode: 'ISO 7010-E020' },
  { id: 'E021', category: 'safe-condition', label: 'Emergency exit (arrow up right)', keywords: ['exit', 'emergency', 'up', 'right'], svgPath: '/pictograms/safe-condition/E021.svg', isoCode: 'ISO 7010-E021' },
  { id: 'E022', category: 'safe-condition', label: 'Emergency exit (arrow down right)', keywords: ['exit', 'emergency', 'down', 'right'], svgPath: '/pictograms/safe-condition/E022.svg', isoCode: 'ISO 7010-E022' },
  { id: 'E023', category: 'safe-condition', label: 'Emergency push-to-exit device', keywords: ['push', 'exit', 'device', 'emergency'], svgPath: '/pictograms/safe-condition/E023.svg', isoCode: 'ISO 7010-E023' },
  { id: 'E024', category: 'safe-condition', label: 'Escape route indicator', keywords: ['escape', 'route', 'indicator', 'direction'], svgPath: '/pictograms/safe-condition/E024.svg', isoCode: 'ISO 7010-E024' },
  { id: 'E025', category: 'safe-condition', label: 'Safe condition E025', keywords: ['safe', 'condition', 'E025', 'safety'], svgPath: '/pictograms/safe-condition/E025.svg', isoCode: 'ISO 7010-E025' },
  { id: 'E026', category: 'safe-condition', label: 'Safe condition E026', keywords: ['safe', 'condition', 'E026', 'safety'], svgPath: '/pictograms/safe-condition/E026.svg', isoCode: 'ISO 7010-E026' },
  { id: 'E027', category: 'safe-condition', label: 'Safe condition E027', keywords: ['safe', 'condition', 'E027', 'safety'], svgPath: '/pictograms/safe-condition/E027.svg', isoCode: 'ISO 7010-E027' },
  { id: 'E028', category: 'safe-condition', label: 'Safe condition E028', keywords: ['safe', 'condition', 'E028', 'safety'], svgPath: '/pictograms/safe-condition/E028.svg', isoCode: 'ISO 7010-E028' },
  { id: 'E029', category: 'safe-condition', label: 'Safe condition E029', keywords: ['safe', 'condition', 'E029', 'safety'], svgPath: '/pictograms/safe-condition/E029.svg', isoCode: 'ISO 7010-E029' },
  { id: 'E030', category: 'safe-condition', label: 'Safe condition E030', keywords: ['safe', 'condition', 'E030', 'safety'], svgPath: '/pictograms/safe-condition/E030.svg', isoCode: 'ISO 7010-E030' },
  { id: 'E031', category: 'safe-condition', label: 'Safe condition E031', keywords: ['safe', 'condition', 'E031', 'safety'], svgPath: '/pictograms/safe-condition/E031.svg', isoCode: 'ISO 7010-E031' },
  { id: 'E032', category: 'safe-condition', label: 'Safe condition E032', keywords: ['safe', 'condition', 'E032', 'safety'], svgPath: '/pictograms/safe-condition/E032.svg', isoCode: 'ISO 7010-E032' },
  { id: 'E033', category: 'safe-condition', label: 'Safe condition E033', keywords: ['safe', 'condition', 'E033', 'safety'], svgPath: '/pictograms/safe-condition/E033.svg', isoCode: 'ISO 7010-E033' },
  { id: 'E034', category: 'safe-condition', label: 'Safe condition E034', keywords: ['safe', 'condition', 'E034', 'safety'], svgPath: '/pictograms/safe-condition/E034.svg', isoCode: 'ISO 7010-E034' },
  { id: 'E035', category: 'safe-condition', label: 'Safe condition E035', keywords: ['safe', 'condition', 'E035', 'safety'], svgPath: '/pictograms/safe-condition/E035.svg', isoCode: 'ISO 7010-E035' },
  { id: 'E036', category: 'safe-condition', label: 'Safe condition E036', keywords: ['safe', 'condition', 'E036', 'safety'], svgPath: '/pictograms/safe-condition/E036.svg', isoCode: 'ISO 7010-E036' },
  { id: 'E037', category: 'safe-condition', label: 'Safe condition E037', keywords: ['safe', 'condition', 'E037', 'safety'], svgPath: '/pictograms/safe-condition/E037.svg', isoCode: 'ISO 7010-E037' },
  { id: 'E038', category: 'safe-condition', label: 'Safe condition E038', keywords: ['safe', 'condition', 'E038', 'safety'], svgPath: '/pictograms/safe-condition/E038.svg', isoCode: 'ISO 7010-E038' },
  { id: 'E039', category: 'safe-condition', label: 'Safe condition E039', keywords: ['safe', 'condition', 'E039', 'safety'], svgPath: '/pictograms/safe-condition/E039.svg', isoCode: 'ISO 7010-E039' },
  { id: 'E040', category: 'safe-condition', label: 'Safe condition E040', keywords: ['safe', 'condition', 'E040', 'safety'], svgPath: '/pictograms/safe-condition/E040.svg', isoCode: 'ISO 7010-E040' },
  { id: 'E041', category: 'safe-condition', label: 'Safe condition E041', keywords: ['safe', 'condition', 'E041', 'safety'], svgPath: '/pictograms/safe-condition/E041.svg', isoCode: 'ISO 7010-E041' },
  { id: 'E042', category: 'safe-condition', label: 'Safe condition E042', keywords: ['safe', 'condition', 'E042', 'safety'], svgPath: '/pictograms/safe-condition/E042.svg', isoCode: 'ISO 7010-E042' },
  { id: 'E043', category: 'safe-condition', label: 'Safe condition E043', keywords: ['safe', 'condition', 'E043', 'safety'], svgPath: '/pictograms/safe-condition/E043.svg', isoCode: 'ISO 7010-E043' },
  { id: 'E044', category: 'safe-condition', label: 'Safe condition E044', keywords: ['safe', 'condition', 'E044', 'safety'], svgPath: '/pictograms/safe-condition/E044.svg', isoCode: 'ISO 7010-E044' },
  { id: 'E045', category: 'safe-condition', label: 'Safe condition E045', keywords: ['safe', 'condition', 'E045', 'safety'], svgPath: '/pictograms/safe-condition/E045.svg', isoCode: 'ISO 7010-E045' },
  { id: 'E046', category: 'safe-condition', label: 'Safe condition E046', keywords: ['safe', 'condition', 'E046', 'safety'], svgPath: '/pictograms/safe-condition/E046.svg', isoCode: 'ISO 7010-E046' },
  { id: 'E047', category: 'safe-condition', label: 'Safe condition E047', keywords: ['safe', 'condition', 'E047', 'safety'], svgPath: '/pictograms/safe-condition/E047.svg', isoCode: 'ISO 7010-E047' },
  { id: 'E048', category: 'safe-condition', label: 'Safe condition E048', keywords: ['safe', 'condition', 'E048', 'safety'], svgPath: '/pictograms/safe-condition/E048.svg', isoCode: 'ISO 7010-E048' },
  { id: 'E049', category: 'safe-condition', label: 'Safe condition E049', keywords: ['safe', 'condition', 'E049', 'safety'], svgPath: '/pictograms/safe-condition/E049.svg', isoCode: 'ISO 7010-E049' },
  { id: 'E050', category: 'safe-condition', label: 'Safe condition E050', keywords: ['safe', 'condition', 'E050', 'safety'], svgPath: '/pictograms/safe-condition/E050.svg', isoCode: 'ISO 7010-E050' },
  { id: 'E051', category: 'safe-condition', label: 'Safe condition E051', keywords: ['safe', 'condition', 'E051', 'safety'], svgPath: '/pictograms/safe-condition/E051.svg', isoCode: 'ISO 7010-E051' },
  { id: 'E052', category: 'safe-condition', label: 'Safe condition E052', keywords: ['safe', 'condition', 'E052', 'safety'], svgPath: '/pictograms/safe-condition/E052.svg', isoCode: 'ISO 7010-E052' },
  { id: 'E053', category: 'safe-condition', label: 'Safe condition E053', keywords: ['safe', 'condition', 'E053', 'safety'], svgPath: '/pictograms/safe-condition/E053.svg', isoCode: 'ISO 7010-E053' },
  { id: 'E054', category: 'safe-condition', label: 'Safe condition E054', keywords: ['safe', 'condition', 'E054', 'safety'], svgPath: '/pictograms/safe-condition/E054.svg', isoCode: 'ISO 7010-E054' },
  { id: 'E055', category: 'safe-condition', label: 'Safe condition E055', keywords: ['safe', 'condition', 'E055', 'safety'], svgPath: '/pictograms/safe-condition/E055.svg', isoCode: 'ISO 7010-E055' },
  { id: 'E056', category: 'safe-condition', label: 'Safe condition E056', keywords: ['safe', 'condition', 'E056', 'safety'], svgPath: '/pictograms/safe-condition/E056.svg', isoCode: 'ISO 7010-E056' },
  { id: 'E057', category: 'safe-condition', label: 'Safe condition E057', keywords: ['safe', 'condition', 'E057', 'safety'], svgPath: '/pictograms/safe-condition/E057.svg', isoCode: 'ISO 7010-E057' },
  { id: 'E058', category: 'safe-condition', label: 'Safe condition E058', keywords: ['safe', 'condition', 'E058', 'safety'], svgPath: '/pictograms/safe-condition/E058.svg', isoCode: 'ISO 7010-E058' },
  { id: 'E059', category: 'safe-condition', label: 'Safe condition E059', keywords: ['safe', 'condition', 'E059', 'safety'], svgPath: '/pictograms/safe-condition/E059.svg', isoCode: 'ISO 7010-E059' },
  { id: 'E060', category: 'safe-condition', label: 'Safe condition E060', keywords: ['safe', 'condition', 'E060', 'safety'], svgPath: '/pictograms/safe-condition/E060.svg', isoCode: 'ISO 7010-E060' },
  { id: 'E061', category: 'safe-condition', label: 'Safe condition E061', keywords: ['safe', 'condition', 'E061', 'safety'], svgPath: '/pictograms/safe-condition/E061.svg', isoCode: 'ISO 7010-E061' },
  { id: 'E062', category: 'safe-condition', label: 'Safe condition E062', keywords: ['safe', 'condition', 'E062', 'safety'], svgPath: '/pictograms/safe-condition/E062.svg', isoCode: 'ISO 7010-E062' },
  { id: 'E063', category: 'safe-condition', label: 'Safe condition E063', keywords: ['safe', 'condition', 'E063', 'safety'], svgPath: '/pictograms/safe-condition/E063.svg', isoCode: 'ISO 7010-E063' },
  { id: 'E064', category: 'safe-condition', label: 'Safe condition E064', keywords: ['safe', 'condition', 'E064', 'safety'], svgPath: '/pictograms/safe-condition/E064.svg', isoCode: 'ISO 7010-E064' },
  { id: 'E065', category: 'safe-condition', label: 'Safe condition E065', keywords: ['safe', 'condition', 'E065', 'safety'], svgPath: '/pictograms/safe-condition/E065.svg', isoCode: 'ISO 7010-E065' },
  { id: 'E067', category: 'safe-condition', label: 'Safe condition E067', keywords: ['safe', 'condition', 'E067', 'safety'], svgPath: '/pictograms/safe-condition/E067.svg', isoCode: 'ISO 7010-E067' },
  { id: 'E068', category: 'safe-condition', label: 'Safe condition E068', keywords: ['safe', 'condition', 'E068', 'safety'], svgPath: '/pictograms/safe-condition/E068.svg', isoCode: 'ISO 7010-E068' },
  { id: 'E070', category: 'safe-condition', label: 'Safe condition E070', keywords: ['safe', 'condition', 'E070', 'safety'], svgPath: '/pictograms/safe-condition/E070.svg', isoCode: 'ISO 7010-E070' },
  { id: 'E072', category: 'safe-condition', label: 'Safe condition E072', keywords: ['safe', 'condition', 'E072', 'safety'], svgPath: '/pictograms/safe-condition/E072.svg', isoCode: 'ISO 7010-E072' },
  { id: 'E073', category: 'safe-condition', label: 'Safe condition E073', keywords: ['safe', 'condition', 'E073', 'safety'], svgPath: '/pictograms/safe-condition/E073.svg', isoCode: 'ISO 7010-E073' },
  { id: 'E074', category: 'safe-condition', label: 'Safe condition E074', keywords: ['safe', 'condition', 'E074', 'safety'], svgPath: '/pictograms/safe-condition/E074.svg', isoCode: 'ISO 7010-E074' },
  { id: 'E075', category: 'safe-condition', label: 'Safe condition E075', keywords: ['safe', 'condition', 'E075', 'safety'], svgPath: '/pictograms/safe-condition/E075.svg', isoCode: 'ISO 7010-E075' },
  { id: 'E076', category: 'safe-condition', label: 'Safe condition E076', keywords: ['safe', 'condition', 'E076', 'safety'], svgPath: '/pictograms/safe-condition/E076.svg', isoCode: 'ISO 7010-E076' },

  // === FIRE EQUIPMENT (F-series) ===
  { id: 'F001', category: 'fire-equipment', label: 'Fire extinguisher', keywords: ['extinguisher', 'fire', 'firefighting', 'safety'], svgPath: '/pictograms/fire-equipment/F001.svg', isoCode: 'ISO 7010-F001' },
  { id: 'F002', category: 'fire-equipment', label: 'Fire hose reel', keywords: ['hose', 'fire', 'reel', 'water'], svgPath: '/pictograms/fire-equipment/F002.svg', isoCode: 'ISO 7010-F002' },
  { id: 'F003', category: 'fire-equipment', label: 'Fire ladder', keywords: ['ladder', 'fire', 'escape', 'climbing'], svgPath: '/pictograms/fire-equipment/F003.svg', isoCode: 'ISO 7010-F003' },
  { id: 'F004', category: 'fire-equipment', label: 'Collection of fire-fighting equipment', keywords: ['collection', 'firefighting', 'equipment', 'station'], svgPath: '/pictograms/fire-equipment/F004.svg', isoCode: 'ISO 7010-F004' },
  { id: 'F005', category: 'fire-equipment', label: 'Fire alarm call point', keywords: ['alarm', 'call point', 'button', 'fire'], svgPath: '/pictograms/fire-equipment/F005.svg', isoCode: 'ISO 7010-F005' },
  { id: 'F006', category: 'fire-equipment', label: 'Fire alarm', keywords: ['alarm', 'fire', 'bell', 'siren'], svgPath: '/pictograms/fire-equipment/F006.svg', isoCode: 'ISO 7010-F006' },
  { id: 'F007', category: 'fire-equipment', label: 'Fire extinguisher (wheeled)', keywords: ['extinguisher', 'wheeled', 'fire', 'large'], svgPath: '/pictograms/fire-equipment/F007.svg', isoCode: 'ISO 7010-F007' },
  { id: 'F008', category: 'fire-equipment', label: 'Firefighting water supply', keywords: ['water', 'supply', 'firefighting', 'hydrant'], svgPath: '/pictograms/fire-equipment/F008.svg', isoCode: 'ISO 7010-F008' },
  { id: 'F009', category: 'fire-equipment', label: 'Fire-fighting equipment storage', keywords: ['equipment', 'storage', 'firefighting', 'cabinet'], svgPath: '/pictograms/fire-equipment/F009.svg', isoCode: 'ISO 7010-F009' },
  { id: 'F010', category: 'fire-equipment', label: 'Emergency fire phone', keywords: ['phone', 'fire', 'emergency', 'telephone'], svgPath: '/pictograms/fire-equipment/F010.svg', isoCode: 'ISO 7010-F010' },
  { id: 'F011', category: 'fire-equipment', label: 'Fire hose reel direction (left)', keywords: ['hose', 'reel', 'direction', 'left'], svgPath: '/pictograms/fire-equipment/F011.svg', isoCode: 'ISO 7010-F011' },
  { id: 'F012', category: 'fire-equipment', label: 'Fire ladder direction', keywords: ['ladder', 'fire', 'direction', 'arrow'], svgPath: '/pictograms/fire-equipment/F012.svg', isoCode: 'ISO 7010-F012' },
  { id: 'F013', category: 'fire-equipment', label: 'Fire alarm call point direction', keywords: ['alarm', 'call point', 'direction', 'arrow'], svgPath: '/pictograms/fire-equipment/F013.svg', isoCode: 'ISO 7010-F013' },
  { id: 'F014', category: 'fire-equipment', label: 'Remote release station', keywords: ['remote', 'release', 'station', 'fire'], svgPath: '/pictograms/fire-equipment/F014.svg', isoCode: 'ISO 7010-F014' },
  { id: 'F015', category: 'fire-equipment', label: 'Fire door/shutter keep clear', keywords: ['fire door', 'shutter', 'keep clear', 'access'], svgPath: '/pictograms/fire-equipment/F015.svg', isoCode: 'ISO 7010-F015' },
  { id: 'F016', category: 'fire-equipment', label: 'Emergency fire phone', keywords: ['phone', 'fire', 'emergency', 'telephone'], svgPath: '/pictograms/fire-equipment/F016.svg', isoCode: 'ISO 7010-F016' },
  { id: 'F017', category: 'fire-equipment', label: 'Underground fire hydrant', keywords: ['underground', 'hydrant', 'fire', 'water'], svgPath: '/pictograms/fire-equipment/F017.svg', isoCode: 'ISO 7010-F017' },
  { id: 'F018', category: 'fire-equipment', label: 'Smoke detector', keywords: ['smoke', 'detector', 'alarm', 'sensor'], svgPath: '/pictograms/fire-equipment/F018.svg', isoCode: 'ISO 7010-F018' },
  { id: 'F019', category: 'fire-equipment', label: 'Sprinkler system', keywords: ['sprinkler', 'system', 'fire', 'suppression'], svgPath: '/pictograms/fire-equipment/F019.svg', isoCode: 'ISO 7010-F019' },
];
